### ISSUE TITLE
WMS not working with categorized style

### ISSUE THREAD

**Issue by honza2** [jirik/layman#45] opened 2020-03-11 20:02 UTC
After uploading layer with categorized style, WMS provide only style, but not raster. WFS working correctly. 
[layer.zip](https://github.com/jirik/layman/files/4320615/layer.zip)

![image](https://user-images.githubusercontent.com/30647487/76458714-3f58e700-63db-11ea-9fbf-293751492b53.png)

**Comment by jirik** [comment] 2020-03-14 18:31
Thanks, I can confirm the bug.

The problem is that all data attributes are converted to lower case when importing into DB. Thus we need to convert also attribute names in SLD to lower case.

XPath: `//ogc:PropertyName/text()`

where `xmlns:ogc="http://www.opengis.net/ogc"`

**Comment by jirik** [comment] 2020-03-14 18:35
Fix will come here: https://github.com/jirik/layman/blob/50c70e421e0c647e64a4372aad38ff60bbff1c7f/src/layman/layer/geoserver/sld.py#L114

**Comment by jirik** [comment] 2020-03-16 16:50
Fixed in https://github.com/jirik/layman/releases/tag/v1.1.8

**Closed by jirik** 2020-03-16 16:50 UTC
Labels: bug
